# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/games" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@games" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/lib/nocow" =
    { device = "/dev/disk/by-uuid/6c4d7ccb-654d-4a82-9e5f-737088e0194a";
      fsType = "btrfs";
      options = [ "subvol=@nocow" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D366-360A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
